# Generated by Django 3.1.7 on 2021-04-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(default='', max_length=120)),
                ('address', models.CharField(default='', max_length=120)),
                ('city', models.CharField(default='', max_length=120)),
                ('state', models.CharField(default='', max_length=120)),
                ('zip_code', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
